apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-laura
spec:
  version: 8.1.0
  count: 1
  elasticsearchRef:
    name: "elasticsearch-laura"
    namespace: elastic
  secureSettings:
  - secretName: kibana-secret-settings
  config:
    xpack.fleet.packages:
    - name: apm
      version: latest
  http:
   service:
     spec:
       type: LoadBalancer
  # this shows how to customize the Kibana pod
  # with labels and resource limits
  podTemplate:
    metadata:
      labels:
        # foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            # cpu: 1
  # 
  # kubectl create secret generic kibana-secret-settings --from-literal=xpack.security.encryptionKey=RqjJTEB9SjA6C3E4FJtE2rfbghd7i0g1ucLqRm1Df1sx58ZlJ5
