apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-laura
spec:
  version: 8.3.0
  count: 1
  elasticsearchRef:
    name: "elasticsearch-laura"
    namespace: elastic
  secureSettings:
  - secretName: kibana-secret-settings
  config:
    # xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch.infra.laura.systems:443"]
    # xpack.fleet.agents.fleet_server.hosts: ["https://fleet.infra.laura.systems:443"]
    # xpack.fleet.packages:
    # - name: system
    #   version: latest
    # - name: elastic_agent
    #   version: latest
    # - name: fleet_server
    #   version: latest
    # - name: apm
    #   version: latest
    # xpack.fleet.agentPolicies:
    # - name: Fleet Server on ECK policy
    #   id: eck-fleet-server
    #   is_default_fleet_server: true
    #   namespace: default
    #   monitoring_enabled:
    #   - logs
    #   - metrics
    #   package_policies:
    #   - name: fleet_server-1
    #     id: fleet_server-1
    #     package:
    #       name: fleet_server
    # - name: Elastic Agent on ECK policy
    #   id: eck-agent
    #   namespace: default
    #   monitoring_enabled:
    #   - logs
    #   - metrics
    #   unenroll_timeout: 900
    #   is_default: true
    #   package_policies:
    #   - name: system-1
    #     id: system-1
    #     package:
    #       name: system
    #   - package:
    #       name: apm
    #     name: apm-1
    #     inputs:
    #     - type: apm
    #       enabled: true
    #       vars:
    #       - name: host
    #         value: apm.infra.laura.systems:443    
  http:
   service:
     spec:
       type: LoadBalancer
  # this shows how to customize the Kibana pod
  # with labels and resource limits
  podTemplate:
    metadata:
      labels:
        # foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            # cpu: 1
  # 
  # kubectl create secret generic kibana-secret-settings --from-literal=xpack.security.encryptionKey=RqjJTEB9SjA6C3E4FJtE2rfbghd7i0g1ucLqRm1Df1sx58ZlJ5
